### PR TITLE
Project Exploration and Fixes

### PR DESCRIPTION
**Pull request by GensIotaDev**
- made csproj slightly more generic with custom macros
- removed unneeded instantiations from Harmony class
- removed obsolete methods
- reworked WorldLayer_PenalizedTiles
- simplified WorldTabUI
- removed extra files from repo

Noticed that ApplyNeighborPenalty can't be hit since no connected Tile has a valid map so I did not test that. Seems intentional but not exactly logical.

### CODE REVIEW

**Comment by Bioscrimson** [comment]
That's very kind of you two!
I am very thankful a new eye could take a look at this code, which has much unnecessary lines that I could not decide on removing it or not.  Many thanks! =D

I see what you mean by the ApplyNeighborPenalty. I do not believe I have really implemented the penalty to other tile properly. The idea is that a penalty (directly related to the level value of adjusted commonality of an animal type) would be applied to adjacent tiles, and should a settlement be created (or the tile visited), the penalty would become a negative factor in the calculations of the adjusted commonality of the animal type in question.

**Comment by GensIotaDev** [comment]
That was me not noticing I commit with the wrong account initially, then realizing fixing it would require nuking the entire branch. Too much effort.

Either way, yes, since its being applied at death and not being saved anywhere, its slightly redundant since any data is immediately lost.

A Dictionary<Tile,Dictionary<animal, penalty>> in the WorldComponent could be the way to go about persistence and since a map component is always created on new map, rather than storing the offsets in the MapComponent, load from the WorldComponent based on that map's tileID.

**Comment by Bioscrimson** [comment]
Oh understandable, ouch!

I see. I will focus on that when I am available to work on code again.
Since it's my first time on github, does merging fuse the modification suggestion to the main code? Or does it just fuse conversation together? I saw a green button and pressed it, I'm still a bit confused as to how it all work, ahah.

**Comment by GensIotaDev** [comment]
The code should be merged with your main branch (you see both main and revert-2-worldui-feature). You would need to fetch the changes from the remote repo (here) to have it change locally but keep in mind, that wipes any non-committed work. The conversation stays unique to the pull request.

**Comment by Bioscrimson** [comment]
I see, alright.

I will take a break for a few days, because I got burned out by coding. I'll come back to it after and work on it back. Just to let you know. =) I appreciate.

**Pull request merged**
